apiVersion: apps/v1
kind: Deployment
metadata:
  name: address
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address
  template:
    metadata:
      labels:
        app: address
    spec:
      containers:
      - name: address
        image: adnanmama/address-service:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
#          initialDelaySeconds: 5
#          timeoutSeconds: 1
#          periodSeconds: 15