apiVersion: extensions/v1beta1
kind: "Ingress"
metadata:
  name: "my-kube-apps-test"
  namespace: "default"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "my-kube-apps"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: address-service
              servicePort: 8080
      host: address.innoventing.net
    - http:
        paths:
          - backend:
              serviceName: person-service
              servicePort: 8080
      host: person.innoventing.net
    - http:
        paths:
          - backend:
              serviceName: employee-service
              servicePort: 8080
      host: employee.innoventing.net

