master:
  adminPassword: "innopass"
  installPlugins:
    - kubernetes:1.12.6
    - workflow-job:2.24
    - workflow-aggregator:2.5
    - credentials-binding:1.16
    - git:3.9.1
    - google-oauth-plugin:0.6
    - google-source-plugin:0.3
  serviceType: ClusterIP
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/ingress.allow-http: "false"
    hostName: jenkins.innoventing.net
    tls:
      - secretName: "innoventing-cert"
        hosts:
          - jenkins.innoventing.net
